name: Maintenance

on:
  schedule:
    - cron: "0 2 * * 1"

  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  dart-pub-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Format the code
        run: dart format bin/

      - name: Upgrade dependencies
        run: dart pub upgrade

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update dependencies
          title: Upgrade dependencies, format the code
          body: |
            - Dependency upgrades
            - Dart format
          branch: maintenance
          branch-suffix: timestamp
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
